import DocumentationVersion from '../models/DocumentationVersion.js';
import Repository from '../models/Repository.js';
import { generateReadme, generateApiDocs } from './readmeGenerator.js';
import { generateWiki } from './wikiGenerator.js';
import { buildKnowledgeBase } from './knowledgeService.js';
import { getIO } from '../socket/index.js';
import { logger } from '../utils/logger.js';

export async function generateAllDocs(repositoryId, userId) {
  const repo = await Repository.findById(repositoryId);
  if (!repo) throw new Error('Repository not found');

  notifyUser(userId, 'info', 'Documentation generation started', repo.fullName);

  await buildKnowledgeBase(repositoryId, userId);

  notifyProgress(userId, repositoryId, 20);

  const readme = await generateReadme(repositoryId);
  await DocumentationVersion.create({
    repositoryId,
    type: 'README',
    title: 'README.md',
    content: readme,
    commitHash: repo.lastCommit,
    generatedBy: 'ai',
  });

  notifyProgress(userId, repositoryId, 40);

  const apiDocs = await generateApiDocs(repositoryId);
  await DocumentationVersion.create({
    repositoryId,
    type: 'API_DOC',
    title: 'API Documentation',
    content: apiDocs,
    commitHash: repo.lastCommit,
    generatedBy: 'ai',
  });

  notifyProgress(userId, repositoryId, 60);

  const wikiPages = await generateWiki(repositoryId);
  for (const page of wikiPages) {
    await DocumentationVersion.create({
      repositoryId,
      type: 'WIKI',
      title: page.title,
      content: page.content,
      commitHash: repo.lastCommit,
      generatedBy: 'ai',
    });
  }

  notifyProgress(userId, repositoryId, 80);

  const architectureDoc = await generateArchitectureDoc(repositoryId, repo);
  await DocumentationVersion.create({
    repositoryId,
    type: 'ARCHITECTURE',
    title: 'Architecture Overview',
    content: architectureDoc,
    commitHash: repo.lastCommit,
    generatedBy: 'ai',
  });

  notifyProgress(userId, repositoryId, 100);

  notifyUser(userId, 'success', 'Documentation generated', `${repo.fullName} — README, Wiki, API docs, and architecture docs created.`);

  return { readme, wiki: wikiPages, apiDocs, architecture: architectureDoc };
}

async function generateArchitectureDoc(repositoryId, repo) {
  return `# Architecture Overview — ${repo.fullName || repo.name}

## Frontend

The frontend is built with HTML5, CSS, and vanilla JavaScript (ES Modules).
It uses a component-based architecture with responsive design and theme support.

## Backend

The backend follows a modular Express.js architecture:
- **Controllers** handle HTTP requests and responses.
- **Services** contain business logic.
- **Models** define data schemas.
- **Routes** map URLs to controllers.
- **Middlewares** handle cross-cutting concerns (auth, validation, rate limiting).

## Database

MongoDB with Mongoose ODM for data storage.

## Real-time

Socket.IO for live updates, progress tracking, and notifications.

## External Services

- GitHub API for repository integration.
- Cloudflare Turnstile for bot protection.
- Resend for transactional emails.
- Groq AI for documentation generation and code understanding.

---

*Architecture documentation auto-generated by Lumora AI.*`;
}

export async function generateDocByType(repositoryId, type, userId) {
  const repo = await Repository.findById(repositoryId);
  if (!repo) throw new Error('Repository not found');

  let content;
  let title;

  switch (type) {
    case 'README':
      content = await generateReadme(repositoryId);
      title = 'README.md';
      break;
    case 'API_DOC':
      content = await generateApiDocs(repositoryId);
      title = 'API Documentation';
      break;
    case 'ARCHITECTURE':
      content = await generateArchitectureDoc(repositoryId, repo);
      title = 'Architecture Overview';
      break;
    case 'WIKI': {
      const pages = await generateWiki(repositoryId);
      for (const page of pages) {
        await DocumentationVersion.create({
          repositoryId,
          type: 'WIKI',
          title: page.title,
          content: page.content,
          commitHash: repo.lastCommit,
          generatedBy: 'ai',
        });
      }
      notifyUser(userId, 'success', 'Wiki generated', `Wiki pages created for ${repo.fullName}`);
      return { wiki: pages };
    }
    default:
      throw new Error('Invalid documentation type');
  }

  const doc = await DocumentationVersion.create({
    repositoryId,
    type,
    title,
    content,
    commitHash: repo.lastCommit,
    generatedBy: 'ai',
  });

  notifyUser(userId, 'success', `${title} generated`, `Documentation updated for ${repo.fullName}`);

  return { [type.toLowerCase()]: doc };
}

function notifyUser(userId, type, title, message) {
  try {
    const io = getIO();
    io.to(`user:${userId}`).emit('notification.new', { type, title, message });
  } catch {}
}

function notifyProgress(userId, repositoryId, progress) {
  try {
    const io = getIO();
    io.to(`user:${userId}`).emit('analysis.progress', {
      repositoryId,
      progress,
      type: 'documentation',
    });
  } catch {}
}
