import { generateCompletion } from './aiService.js';
import KnowledgeChunk from '../models/KnowledgeChunk.js';
import Repository from '../models/Repository.js';
import ApiEndpoint from '../models/ApiEndpoint.js';
import Dependency from '../models/Dependency.js';
import EnvironmentVariable from '../models/EnvironmentVariable.js';
import GraphNode from '../models/GraphNode.js';
import { logger } from '../utils/logger.js';

export async function generateWiki(repositoryId) {
  const repo = await Repository.findById(repositoryId);
  if (!repo) throw new Error('Repository not found');

  const pages = await Promise.all([
    generateWikiHome(repositoryId, repo),
    generateArchitecturePage(repositoryId, repo),
    generateAuthPage(repositoryId),
    generateDatabasePage(repositoryId),
    generateApiReferencePage(repositoryId),
    generateDevelopmentGuide(repositoryId, repo),
    generateDeploymentPage(repositoryId, repo),
  ]);

  return pages;
}

async function generateWikiHome(repositoryId, repo) {
  const content = `# ${repo.fullName || repo.name}

${repo.description || 'No description available.'}

## Technology Stack

- **Language:** ${repo.language || 'Unknown'}
- **Files:** ${repo.filesCount || 'N/A'}

## Quick Start

\`\`\`bash
git clone https://github.com/${repo.fullName || '...'}
cd ${repo.name || 'project'}
# Install dependencies (refer to README for instructions)
\`\`\`

---

*This wiki is auto-generated by Lumora AI.*`;

  return { title: 'Home', slug: 'Home', content, type: 'WIKI' };
}

async function generateArchitecturePage(repositoryId, repo) {
  const nodes = await GraphNode.find({ repositoryId });
  const fileNodes = nodes.filter((n) => n.type === 'file');
  const routeNodes = nodes.filter((n) => n.type === 'route');
  const classNodes = nodes.filter((n) => n.type === 'class');

  let content = `# Architecture — ${repo.name || 'Project'}\n\n`;
  content += `## Overview\n\n${repo.description || 'Repository architecture overview.'}\n\n`;

  content += `## Project Structure\n\n`;
  content += `\`\`\`\n`;
  content += `${repo.name || 'project'}/\n`;

  const dirs = new Set();
  for (const node of fileNodes) {
    const parts = (node.name || '').split('/');
    if (parts.length > 1) {
      for (let i = 0; i < parts.length - 1; i++) {
        dirs.add('  '.repeat(i) + parts.slice(0, i + 1).join('/') + '/');
      }
    }
  }
  content += [...dirs].sort().join('\n');
  content += `\n\`\`\`\n\n`;

  if (routeNodes.length > 0) {
    content += `## API Routes\n\n`;
    content += `The following API routes were detected:\n\n`;
    for (const route of routeNodes) {
      content += `- \`${route.name}\`\n`;
    }
    content += '\n';
  }

  if (classNodes.length > 0) {
    content += `## Key Classes\n\n`;
    for (const cls of classNodes) {
      const extends_ = cls.metadata?.extends;
      content += `- **${cls.name}**${extends_ ? ` extends \`${extends_}\`` : ''}\n`;
    }
    content += '\n';
  }

  content += `---
*Architecture page auto-generated by Lumora AI.*`;

  return { title: 'Architecture', slug: 'Architecture', content, type: 'WIKI' };
}

async function generateAuthPage(repositoryId) {
  const endpoints = await ApiEndpoint.find({ repositoryId });
  const authEndpoints = endpoints.filter((e) =>
    e.path.toLowerCase().includes('auth') ||
    e.path.toLowerCase().includes('login') ||
    e.path.toLowerCase().includes('register')
  );

  let content = `# Authentication\n\n`;
  content += `## Overview\n\n`;
  content += `This section describes the authentication flow.\n\n`;

  if (authEndpoints.length > 0) {
    content += `## Auth Endpoints\n\n`;
    for (const ep of authEndpoints) {
      content += `### \`${ep.method} ${ep.path}\`\n`;
      content += `- **File:** \`${ep.file || 'Unknown'}\`\n`;
      if (ep.middleware && ep.middleware.length > 0) {
        content += `- **Middleware:** ${ep.middleware.join(', ')}\n`;
      }
      content += '\n';
    }
  } else {
    content += `No authentication-specific endpoints were detected.\n\n`;
  }

  content += `## Security Considerations\n\n`;
  content += `- Passwords should always be hashed\n`;
  content += `- Use JWT or session-based authentication\n`;
  content += `- Implement rate limiting on auth endpoints\n`;
  content += `- Validate all user input\n\n`;

  content += `---
*Auth documentation auto-generated by Lumora AI.*`;

  return { title: 'Authentication', slug: 'Authentication', content, type: 'WIKI' };
}

async function generateDatabasePage(repositoryId) {
  const nodes = await GraphNode.find({ repositoryId });
  const modelNodes = nodes.filter((n) => n.type === 'model');

  let content = `# Database\n\n`;
  content += `## Schema\n\n`;

  if (modelNodes.length > 0) {
    for (const model of modelNodes) {
      content += `### ${model.name}\n\n`;
      if (model.metadata?.fields) {
        content += `| Field | Type |\n|---|---|\n`;
        for (const [field, type] of Object.entries(model.metadata.fields)) {
          content += `| ${field} | ${type} |\n`;
        }
        content += '\n';
      }
    }
  } else {
    content += `No database models were detected through static analysis.\n\n`;
  }

  content += `---
*Database documentation auto-generated by Lumora AI.*`;

  return { title: 'Database', slug: 'Database', content, type: 'WIKI' };
}

async function generateApiReferencePage(repositoryId) {
  const endpoints = await ApiEndpoint.find({ repositoryId });

  let content = `# API Reference\n\n`;
  content += `## Endpoints\n\n`;

  if (endpoints.length === 0) {
    content += `No API endpoints were detected.\n`;
  } else {
    for (const ep of endpoints) {
      content += `### ${ep.method} \`${ep.path}\`\n\n`;
      content += `- **File:** \`${ep.file || 'Unknown'}\`\n`;
      if (ep.function) content += `- **Handler:** \`${ep.function}\`\n`;
      if (ep.middleware && ep.middleware.length > 0) {
        content += `- **Middleware:** ${ep.middleware.join(', ')}\n`;
      }
      content += '\n---\n\n';
    }
  }

  content += `---
*API reference auto-generated by Lumora AI.*`;

  return { title: 'API Reference', slug: 'API-Reference', content, type: 'WIKI' };
}

async function generateDevelopmentGuide(repositoryId, repo) {
  let content = `# Development Guide\n\n`;
  content += `## Getting Started\n\n`;
  content += `1. Clone the repository\n`;
  content += `2. Install dependencies\n`;
  content += `3. Set up environment variables\n`;
  content += `4. Run the development server\n\n`;

  content += `## Project Structure\n\n`;
  content += `The project follows a modular architecture:\n\n`;
  content += `- \`controllers/\` — Request handlers\n`;
  content += `- \`services/\` — Business logic\n`;
  content += `- \`models/\` — Data models\n`;
  content += `- \`routes/\` — Route definitions\n`;
  content += `- \`middlewares/\` — Express middleware\n`;
  content += `- \`utils/\` — Utility functions\n`;
  content += `- \`config/\` — Configuration\n\n`;

  content += `## Code Style\n\n`;
  content += `Follow the existing code patterns in the repository.\n\n`;

  content += `## Testing\n\n`;
  content += `Refer to the test directory for existing tests.\n\n`;

  content += `---
*Development guide auto-generated by Lumora AI.*`;

  return { title: 'Development Guide', slug: 'Development-Guide', content, type: 'WIKI' };
}

async function generateDeploymentPage(repositoryId, repo) {
  let content = `# Deployment\n\n`;
  content += `## Production Setup\n\n`;

  const deps = await Dependency.find({ repositoryId });
  const hasDocker = deps.some((d) => d.name === 'docker' || d.ecosystem === 'system');

  if (hasDocker) {
    content += `### Docker\n\n`;
    content += `This project appears to use Docker:\n\n`;
    content += `\`\`\`bash\n`;
    content += `docker build -t ${repo.name || 'app'} .\n`;
    content += `docker run -p 3000:3000 ${repo.name || 'app'}\n`;
    content += `\`\`\`\n\n`;
  }

  content += `### Environment Variables\n\n`;
  content += `Ensure all required environment variables are set in production.\n\n`;

  content += `### Build\n\n`;
  content += `\`\`\`bash\n`;
  content += `npm run build\n`;
  content += `npm start\n`;
  content += `\`\`\`\n\n`;

  content += `---
*Deployment guide auto-generated by Lumora AI.*`;

  return { title: 'Deployment', slug: 'Deployment', content, type: 'WIKI' };
}
